# PC5 vs CoG–SP on hardest 20% hetero panel → LaTeX table.
# Usage: julia --project=. src/analyze_comparison_pc5_cog_hetero.jl

using Printf
using Statistics

const CSV = joinpath(@__DIR__, "..", "results", "comparison_pc5_cog_hetero.csv")
const LATEX_PATH = joinpath(@__DIR__, "..", "latex", "tables", "ablation_pc5_cog_hetero_hard.tex")
const LAYOUTS = ["RAND", "CLUS", "CPCD"]

function parse_inst(name)
    parts = split(name, "_")
    sz = parse(Int, parts[1])
    lay = parts[2]
    bx = parse(Int, parts[3])
    return sz, lay, bx
end

rows = Tuple{String,Int,String,Float64,Int,Int}[]
for line in eachline(CSV)
    startswith(line, "instance") && continue
    p = split(line, ",")
    push!(rows, (
        strip(p[1]), parse(Int, p[2]), strip(p[3]),
        parse(Float64, p[4]), parse(Int, p[6]), parse(Int, p[7]),
    ))
end
@printf("Loaded %d rows\n", length(rows))

cls_objs  = Dict{Tuple{Int,String,Int,String}, Vector{Float64}}()
cls_calls = Dict{Tuple{Int,String,Int,String}, Vector{Int}}()
for (inst, _, oracle, obj, nc, _) in rows
    sz, lay, bx = parse_inst(inst)
    push!(get!(cls_objs, (sz, lay, bx, oracle), Float64[]), obj)
    push!(get!(cls_calls, (sz, lay, bx, oracle), Int[]), nc)
end

pairs = Dict{String, Dict{String, Float64}}()
for (inst, _, oracle, obj, _, _) in rows
    get!(pairs, inst, Dict{String, Float64}())[oracle] = obj
end
cls_wins = Dict{Tuple{Int,String,Int}, Int}()
cls_np = Dict{Tuple{Int,String,Int}, Int}()
for (inst, d) in pairs
    haskey(d, "3csp_pc5") && haskey(d, "3csp_cog") || continue
    sz, lay, bx = parse_inst(inst)
    k = (sz, lay, bx)
    cls_np[k] = get(cls_np, k, 0) + 1
    d["3csp_cog"] < d["3csp_pc5"] && (cls_wins[k] = get(cls_wins, k, 0) + 1)
end

groups = sort(collect(keys(cls_objs)))  # (sz, lay, bx, oracle)
szbx_keys = sort(unique([(sz, lay, bx) for (sz, lay, bx, _) in keys(cls_objs)]))

is_best_ttd(x, a, b) = isapprox(x, min(a, b); rtol=0, atol=1e-6)
fmt_calls(x) = @sprintf("%.1f", x)
fmt_ttd(x, a, b; dec=1) =
    dec == 2 ?
    (is_best_ttd(x, a, b) ? @sprintf("\\textbf{%.2f}", x) : @sprintf("%.2f", x)) :
    (is_best_ttd(x, a, b) ? @sprintf("\\textbf{%.1f}", x) : @sprintf("%.1f", x))
fmt_delta(pc5, cog) = begin
    pct = 100 * (cog - pc5) / pc5
    pct >= 0 ? @sprintf("\$+\$%.2f", pct) : @sprintf("\$-\$%.2f", abs(pct))
end

eol = " \\\\\n"

function write_latex_table()
    total_pc5 = Float64[]
    total_cog = Float64[]
    tot_c_pc5 = 0
    tot_c_cog = 0
    tot_w = 0
    tot_n = 0

    open(LATEX_PATH, "w") do io
    println(io, "% Auto-generated by analyze_comparison_pc5_cog_hetero.jl")
    println(io, raw"\begin{tabular}{@{}l r | r r | r r | r r@{}}")
    println(io, raw"  \toprule")
    print(io, raw"  \multirow{2}{*}{Instance class} & \multirow{2}{*}{$n$}")
    print(io, raw" & \multicolumn{2}{c|}{3C-SP + PC5}")
    print(io, raw" & \multicolumn{2}{c|}{3C-SP + CoG--SP}")
    println(io, raw" & \multirow{2}{*}{$\Delta$\%} & \multirow{2}{*}{Wins CoG}" * eol)
    println(io, raw"  \cmidrule(lr){3-4}\cmidrule(lr){5-6}")
    println(io, raw"  & & Calls (M) & TTD & Calls (M) & TTD & &" * eol)
    println(io, raw"  \midrule")

    last_sz = 0
    for (sz, lay, bx) in szbx_keys
        g_pc5 = get(cls_objs, (sz, lay, bx, "3csp_pc5"), Float64[])
        g_cog = get(cls_objs, (sz, lay, bx, "3csp_cog"), Float64[])
        isempty(g_pc5) && continue
        c_pc5 = sum(get(cls_calls, (sz, lay, bx, "3csp_pc5"), Int[]))
        c_cog = sum(get(cls_calls, (sz, lay, bx, "3csp_cog"), Int[]))
        m_pc5, m_cog = mean(g_pc5), mean(g_cog)
        n = length(g_pc5)
        w = get(cls_wins, (sz, lay, bx), 0)
        np = get(cls_np, (sz, lay, bx), n)

        sz_str = sz == 50 ? "50\\,req" : sz == 75 ? "75\\,req" : "100\\,req"
        bx_str = bx == 2 ? "2\\,box" : "3\\,box"
        print(io, "  $(sz_str), $(lay), $(bx_str) & $n")
        print(io, " & $(fmt_calls(c_pc5 / 1e6)) & $(fmt_ttd(m_pc5, m_pc5, m_cog))")
        print(io, " & $(fmt_calls(c_cog / 1e6)) & $(fmt_ttd(m_cog, m_pc5, m_cog))")
        println(io, " & $(fmt_delta(m_pc5, m_cog)) & $w/$np" * eol)

        append!(total_pc5, g_pc5)
        append!(total_cog, g_cog)
        tot_c_pc5 += c_pc5
        tot_c_cog += c_cog
        tot_w += w
        tot_n += np
        last_sz = sz
    end

    m_pc5, m_cog = mean(total_pc5), mean(total_cog)
    println(io, raw"  \midrule")
    print(io, "  \\textbf{Overall} & $(length(total_pc5))")
    print(io, " & $(fmt_calls(tot_c_pc5 / 1e6)) & $(fmt_ttd(m_pc5, m_pc5, m_cog; dec=2))")
    print(io, " & $(fmt_calls(tot_c_cog / 1e6)) & $(fmt_ttd(m_cog, m_pc5, m_cog; dec=2))")
    println(io, " & $(fmt_delta(m_pc5, m_cog)) & $tot_w/$tot_n" * eol)
    println(io, raw"  \bottomrule")
    println(io, raw"\end{tabular}")
    end
    println("LaTeX table written to: $LATEX_PATH")
end

write_latex_table()
