# Summarize and export LaTeX for 3C-SP PC2 (3csp) vs CoG–SP (3csp_cog).
# Usage: julia --project=. src/analyze_comparison_cog_sp.jl

using Printf
using Statistics

const CSV = joinpath(@__DIR__, "..", "results", "comparison_oracle_cog_sp.csv")
const LAYOUTS = ["RAND", "CLUS", "CPCD"]
const LATEX_PATH = joinpath(@__DIR__, "..", "latex", "tables", "ablation_3csp_cog_sp.tex")

isfile(CSV) || error("Missing $CSV — merge worker CSVs first.")

function parse_inst(name)
    parts = split(name, "_")
    return parse(Int, parts[1]), parts[2], parse(Int, parts[3])
end

rows = Tuple{String,Int,String,Float64,Int,Int}[]
for line in eachline(CSV)
    startswith(line, "instance") && continue
    p = split(line, ",")
    push!(rows, (
        strip(p[1]), parse(Int, p[2]), strip(p[3]),
        parse(Float64, p[4]), parse(Int, p[6]), parse(Int, p[7]),
    ))
end

@printf("Loaded %d rows from %s\n\n", length(rows), CSV)

cls_objs  = Dict{Tuple{Int,String,Int,String}, Vector{Float64}}()
cls_calls = Dict{Tuple{Int,String,Int,String}, Vector{Int}}()
for (inst, seed, oracle, obj, nc, _) in rows
    sz, lay, bx = parse_inst(inst)
    push!(get!(cls_objs, (sz, lay, bx, oracle), Float64[]), obj)
    push!(get!(cls_calls, (sz, lay, bx, oracle), Int[]), nc)
end

pairs = Dict{Tuple{String,Int}, Dict{String,Float64}}()
for (inst, seed, oracle, obj, _, _) in rows
    get!(pairs, (inst, seed), Dict{String, Float64}())[oracle] = obj
end

szbx_wins = Dict{Tuple{Int,Int}, Int}()
szbx_np   = Dict{Tuple{Int,Int}, Int}()
for ((inst, seed), d) in pairs
    (haskey(d, "3csp") && haskey(d, "3csp_cog")) || continue
    sz, _, bx = parse_inst(inst)
    k = (sz, bx)
    szbx_np[k] = get(szbx_np, k, 0) + 1
    d["3csp_cog"] < d["3csp"] && (szbx_wins[k] = get(szbx_wins, k, 0) + 1)
end

szbx_groups = sort(unique([(sz, bx) for (sz, lay, bx, _) in keys(cls_objs)]))

function write_latex_table()
    is_best_ttd(x, a, b) = isapprox(x, min(a, b); rtol=0, atol=1e-6)
    fmt_calls(x) = @sprintf("%.1f", x)
    fmt_ttd1(x, a, b) =
        is_best_ttd(x, a, b) ? @sprintf("\\textbf{%.1f}", x) : @sprintf("%.1f", x)
    fmt_ttd2(x, a, b) =
        is_best_ttd(x, a, b) ? @sprintf("\\textbf{%.2f}", x) : @sprintf("%.2f", x)
    fmt_delta(pc2, cog) = begin
        pct = 100 * (cog - pc2) / pc2
        pct >= 0 ? @sprintf("\$+\$%.2f", pct) : @sprintf("\$-\$%.2f", abs(pct))
    end

    total_pc2 = Float64[]
    total_cog = Float64[]
    tot_c_pc2 = 0
    tot_c_cog = 0
    tot_w_cog = 0
    tot_np = 0

    eol = " \\\\\n"
    open(LATEX_PATH, "w") do io
        println(io, "% Auto-generated by analyze_comparison_cog_sp.jl")
        println(io, raw"\begin{tabular}{@{}l r | r r | r r | r r@{}}")
        println(io, raw"  \toprule")
        print(io, raw"  \multirow{2}{*}{Instance class} & \multirow{2}{*}{$n$}")
        print(io, raw" & \multicolumn{2}{c|}{3C-SP + PC2 (shelf)}")
        print(io, raw" & \multicolumn{2}{c|}{3C-SP + CoG--SP}")
        println(io, raw" & \multirow{2}{*}{$\Delta$\%} & \multirow{2}{*}{Wins CoG}" * eol)
        println(io, raw"  \cmidrule(lr){3-4}\cmidrule(lr){5-6}")
        println(io, raw"  & & Calls (M) & TTD & Calls (M) & TTD & &" * eol)
        println(io, raw"  \midrule")

        for (sz, bx) in szbx_groups
            g_pc2 = Float64[]
            g_cog = Float64[]
            c_pc2 = 0
            c_cog = 0
            for lay in LAYOUTS
                append!(g_pc2, get(cls_objs, (sz, lay, bx, "3csp"), Float64[]))
                append!(g_cog, get(cls_objs, (sz, lay, bx, "3csp_cog"), Float64[]))
                c_pc2 += sum(get(cls_calls, (sz, lay, bx, "3csp"), Int[]))
                c_cog += sum(get(cls_calls, (sz, lay, bx, "3csp_cog"), Int[]))
            end
            isempty(g_pc2) && continue

            m_pc2 = mean(g_pc2)
            m_cog = mean(g_cog)
            n = length(g_pc2)
            w_cog = get(szbx_wins, (sz, bx), 0)
            np = get(szbx_np, (sz, bx), n)

            sz_str = sz == 50 ? "50\\,req" : sz == 75 ? "75\\,req" : "100\\,req"
            bx_str = bx == 2 ? "2\\,box/req" : "3\\,box/req"

            print(io, "  $(sz_str), $(bx_str) & $n")
            print(io, " & $(fmt_calls(c_pc2 / 1e6)) & $(fmt_ttd1(m_pc2, m_pc2, m_cog))")
            print(io, " & $(fmt_calls(c_cog / 1e6)) & $(fmt_ttd1(m_cog, m_pc2, m_cog))")
            println(io, " & $(fmt_delta(m_pc2, m_cog)) & $w_cog/$np" * eol)

            append!(total_pc2, g_pc2)
            append!(total_cog, g_cog)
            tot_c_pc2 += c_pc2
            tot_c_cog += c_cog
            tot_w_cog += w_cog
            tot_np += np
        end

        m_pc2 = mean(total_pc2)
        m_cog = mean(total_cog)
        println(io, raw"  \midrule")
        print(io, "  \\textbf{Overall} & $(length(total_pc2))")
        print(io, " & $(fmt_calls(tot_c_pc2 / 1e6)) & $(fmt_ttd2(m_pc2, m_pc2, m_cog))")
        print(io, " & $(fmt_calls(tot_c_cog / 1e6)) & $(fmt_ttd2(m_cog, m_pc2, m_cog))")
        println(io, " & $(fmt_delta(m_pc2, m_cog)) & $tot_w_cog/$tot_np" * eol)
        println(io, raw"  \bottomrule")
        println(io, raw"\end{tabular}")
    end
    println("\nLaTeX table written to: $LATEX_PATH")
end

for o in ("3csp", "3csp_cog")
    sub = [r for r in rows if r[3] == o]
    objs = [r[4] for r in sub]
    calls = [r[5] for r in sub]
    pce = [r[6] / r[5] for r in sub if r[5] > 0]
    @printf("%-10s  mean_TTD=%8.2f  median=%8.2f  mean_calls=%12.0f  mean_pce=%.4f\n",
            o, mean(objs), median(objs), mean(calls), mean(pce))
end

deltas = Float64[]
for ((_, _), d) in pairs
    haskey(d, "3csp") && haskey(d, "3csp_cog") || continue
    s, c = d["3csp"], d["3csp_cog"]
    push!(deltas, 100 * (c - s) / s)
end
wins_cog = count(<(0), deltas)
wins_pc2 = count(>(0), deltas)
println()
@printf("Paired: CoG better %d  PC2 better %d  ties %d  mean_delta%%=%.3f\n",
        wins_cog, wins_pc2, count(==(0), deltas), mean(deltas))

write_latex_table()
